/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: tedpermana (https://sketchfab.com/tedpermana)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-trash-bag-69876d51e2f0462498b81dffe3387ae0
Title: Low Poly Trash Bag
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from "three"
import { useFrame } from '@react-three/fiber'

export function Trash(props: any) {
  const { nodes, materials } = useGLTF('/models/low_poly_trash_bag.glb')
  const group = useRef<THREE.Group>(null);

  useFrame((state) => {
      const trash = group.current;
      if (!trash) return;
  
      trash.position.y = Math.sin(state.clock.elapsedTime * 5) * 0.05;
      trash.rotation.x = Math.sin(state.clock.elapsedTime * 5) * 0.2;
      trash.rotation.z = Math.sin(state.clock.elapsedTime * 4) * 0.2;
    });

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.wire_204204204}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.006}
      />
    </group>
  )
}

useGLTF.preload('/models/low_poly_trash_bag.glb')